### ISSUE TITLE
Can the pose label of Assembly101 be used?

### ISSUE THREAD

**Issue by fandulu** [bestonebyone/HANDS2022_Assembly101#1]
The challenge page mentions that "Semi/Self-supervised Two-hands 3D Pose Estimation during Hand-object and Hand-hand interactions using the recently introduced [Assembly101 dataset](https://assembly-101.github.io/). The dataset provides mutli-view captured videos of hand-object interaction during assembling and disassembling of toy-vehicles **without pose annotations.**"

But Assembly101 seems to have the pose annotations, can these annotations be used for the training?

**Comment by bestonebyone** [comment]
No. You may find the instruction on this [website](https://sites.google.com/view/hands2022/assembly101?authuser=0). For a fair comparison, we limit the use of training data. The ''pose annotations'' you mentioned in Assembly101 are based on [MEgATrack](https://dl.acm.org/doi/pdf/10.1145/3386569.3392452), which uses four egocentric views and serves as a baseline for our challenge. They are not 3D annotations, and our 3D annotations are human annotated. The results of MEgATrack can be found in our CodaLab. Its xyz_mean3d is 4.7cm.

**Comment by fandulu** [comment]
Got it. Thanks very much for your detailed explanation.
